const ProductData = [
  {
    image: "/react-furniture-shop/images/product1.png",
    name: "Storm Small Jug",
    oldPrice: 23.9,
    newPrice: 19.12,
  },
  {
    image: "/react-furniture-shop/images/product2.png",
    name: "Pia Chair",
    oldPrice: 35.9,
    newPrice: 28.72,
  },
  {
    image: "/react-furniture-shop/images/product3.png",
    name: "Slide Table",
    oldPrice: 36.9,
    newPrice: 29.0,
  },
  {
    image: "/react-furniture-shop/images/product4.png",
    name: "Laundry Baskets",
    oldPrice: 36.9,
    newPrice: 29.0,
  },
];

export default ProductData;
