import product1 from "../../assets/images/product1.png";
import product2 from "../../assets/images/product2.png";
import product3 from "../../assets/images/product3.png";
import product4 from "../../assets/images/product4.png";
const ProductData = [
  {
    image: product1,
    name: "Storm Small Jug",
    oldPrice: 23.9,
    newPrice: 19.12,
  },
  {
    image: product2,
    name: "Pia Chair",
    oldPrice: 35.9,
    newPrice: 28.72,
  },
  {
    image: product3,
    name: "Slide Table",
    oldPrice: 36.9,
    newPrice: 29.0,
  },
  {
    image: product4,
    name: "Laundry Baskets",
    oldPrice: 36.9,
    newPrice: 29.0,
  },
];

export default ProductData;
